CREATE DATABASE IF NOT EXISTS way2;

USE way2;

CREATE TABLE IF NOT EXISTS Branch(
    id INT NOT NULL AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS City(
    id INT NOT NULL AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS State(
    id INT NOT NULL AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Person(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    Dealership BOOLEAN NOT NULL DEFAULT 0,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    City INT,
    State INT,
    Branch INT,
    PRIMARY KEY (id),
    CONSTRAINT FK_PersonCity FOREIGN KEY (City) REFERENCES City(id),
    CONSTRAINT FK_PersonState FOREIGN KEY (State) REFERENCES State(id),
    CONSTRAINT FK_PersonBranch FOREIGN KEY (Branch) REFERENCES Branch(id)
);

ALTER TABLE Branch ADD INDEX (id);
ALTER TABLE City ADD INDEX (id);
ALTER TABLE State ADD INDEX (id);
ALTER TABLE Person ADD INDEX (id);
